# application.properties
quarkus.container-image.group=joelmaykon
quarkus.container-image.registry=docker.io
quarkus.container-image.name=atomant-integration
quarkus.container-image.tag=latest
quarkus.container-image.build=true
