# application.properties
quarkus.container-image.group=joelmaykon
quarkus.container-image.registry=docker.io
quarkus.container-image.name=atomant-ingestion
quarkus.container-image.tag=latest
quarkus.container-image.build=true

# MicroProfile REST Client URLs
# These base paths can be overridden in staging/production environments.
org.acme.ingestion.infrastructure.client.CvmClient/mp-rest/url=https://api.cvm.gov.br
org.acme.ingestion.infrastructure.client.BacenClient/mp-rest/url=https://api.bcb.gov.br
org.acme.ingestion.infrastructure.client.IpeadataClient/mp-rest/url=http://www.ipeadata.gov.br/api

# Fault Tolerance Configuration (Defaults)
# Set default values for circuit breakers and retries
quarkus.fault-tolerance.global.enabled=true
