# application.properties
quarkus.container-image.group=joelmaykon
quarkus.container-image.registry=docker.io
quarkus.container-image.name=atomant-audit
quarkus.container-image.tag=latest
quarkus.container-image.build=true

# Database Configuration (PostgreSQL)
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=audit_admin
%prod.quarkus.datasource.password=audit_secret
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/audit_db

# Hibernate & Panache configuration
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.jdbc.statement-batch-size=50
