# Project identification
sonar.projectKey=joelmaykon-monorepo
sonar.projectName=Joel Maykon Workspace
sonar.projectVersion=1.0

# Base directory (One level up from @devops)
sonar.projectBaseDir=..

# Path to the source directories
sonar.sources=@angular/financial/src,@java/atomant-auth/src/main/java,@python/poetry

# Exclusions
sonar.exclusions=**/node_modules/**,**/target/**,**/.venv/**,**/dist/**

# Binary folders (Required for Java analysis)
sonar.java.binaries=@java/atomant-auth/target/classes

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Python specific configuration
# sonar.python.version=3.11
