# application.properties
quarkus.container-image.group=joelmaykon
quarkus.container-image.registry=docker.io
quarkus.container-image.name=atomant-investment-core
quarkus.container-image.tag=latest
quarkus.container-image.build=true

# Database Configuration (PostgreSQL)
# Dev Services will automatically spin up a test PostgreSQL container in Dev/Test mode.
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=investment_admin
%prod.quarkus.datasource.password=investment_secret
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/investment_db

# Hibernate configuration
quarkus.hibernate-orm.database.generation=update

# REST Client Configuration
org.acme.investment.infrastructure.client.DepartmentClient/mp-rest/url=http://localhost:8089

# Test Database Configuration (H2)
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=


