# application.properties
quarkus.container-image.group=joelmaykon
quarkus.container-image.registry=docker.io
quarkus.container-image.name=atomant-investment-core
quarkus.container-image.tag=latest
quarkus.container-image.build=true

# Database Configuration (PostgreSQL)
# Dev Services will automatically spin up a test PostgreSQL container in Dev/Test mode.
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=investment_admin
%prod.quarkus.datasource.password=investment_secret
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/investment_db

# Hibernate configuration
quarkus.hibernate-orm.database.generation=update
